[build]
  command = "npm run build:netlify"
  publish = "build/client"

[dev]
  command = "remix vite:dev"

[build.environment]
  NODE_VERSION = "20"
  NPM_CONFIG_FETCH_RETRIES = "5"
  NPM_CONFIG_FETCH_RETRY_FACTOR = "10"
  NPM_CONFIG_FETCH_RETRY_MINTIMEOUT = "20000"
  NPM_CONFIG_TIMEOUT = "600000"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/remix-server"
  status = 200
